### ISSUE TITLE
Helper function is private

### ISSUE THREAD

**Issue by th0mas** [dwyl/rbac#10]
`transform_roles_string_to_list_of_ints/1` is a private function as when reviewing #7 I believed this would only be used internally, however this would be a useful function to have when persisting roles to a database.

**Comment by th0mas** [comment]
@nelsonic Are you happy to rename this function to `parse_role_string` to save on keypresses?

**Comment by nelsonic** [comment]
@th0mas you IDE should autocomplete the function name, but that function name makes sense so feel free to update it. 👍
