### ISSUE TITLE
Duplicate @doc

### ISSUE THREAD

**Issue by samhstn** [dwyl/rbac#14]
After cloning the repo, then running: `mix do deps.get, compile`, we get the following warning:

```
warning: redefining @doc attribute previously set at line 145.

Please remove the duplicate docs. If instead you want to override a previously defined @doc, attach the @doc attribute to a function head:

    @doc """
    new docs
    """
    def has_role?(...)

  lib/rbac.ex:164: RBAC.has_role?/2
```

- [ ] We should remove this duplicate doc causing this warning.

**Comment by nelsonic** [comment]
yeah, this was left in as we were in the process of adding more functions, but good to just remove for now. thanks. 👍
