### ISSUE TITLE
Tests for #7 don't pass

### ISSUE THREAD

**Issue by th0mas** [dwyl/rbac#8]
When attempting to refractor some code for #7, I ran the test suite to make sure my development environment worked. However, I can't get one of the tests to pass without changing any code:

![image](https://user-images.githubusercontent.com/9089056/93206463-57763e00-f751-11ea-9aa7-00c8da145eac.png)

**Comment by th0mas** [comment]
Don't seem to pass on Travis either now:

![image](https://user-images.githubusercontent.com/9089056/93207031-3b26d100-f752-11ea-84ba-61b6fa52e329.png)

**Comment by nelsonic** [comment]
@th0mas good catch. the `length` should be **`8`** unless the `app` associated has custom roles. 
I was using my `AUTH_API_KEY` for an `app` that had 9 roles to confirm that a custom role is retrieved. 👍

**Comment by th0mas** [comment]
Fixed now...?

**Comment by nelsonic** [comment]
@th0mas I created a custom role for the App to confirm. 
Don't worry, it's not an intermittent failure. 
But it will be "brittle" until we restrict CRUD access to roles (_as you have already pointed out_) https://github.com/dwyl/auth/issues/116
