### ISSUE TITLE
Function for listing roles available for an app.

### ISSUE THREAD

**Issue by th0mas** [dwyl/rbac#9]
A function for listing roles available for an app would be really useful e.g. for generating drop-down menus of available roles.

These could be easily pulled from ETS where they are already cached.

Something like

```elixir
RBAC.get_approles/1
```

would work well with the existing `RBAC.get_approles/2` function

**Comment by nelsonic** [comment]
https://diff.hex.pm/diff/rbac/0.5.1..0.5.2
